import type { Metadata } from "next";
import GNB from "@/components/GNB";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@2.0/nanumsquare.css"
        />
      </head>
      <body className="antialiased font-[NanumSquare]">
        <header className=" border-b border-[#E2E8F0] h-15">
          <GNB />
        </header>
        <main className="max-w-300 mx-auto py-8">{children}</main>
      </body>
    </html>
  );
}
