import type { Metadata } from "next";
import GNB from "@/components/GNB";
import "./globals.css";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@2.0/nanumsquare.css"
        />
      </head>
      <body className="antialiased font-[NanumSquare] min-h-screen flex flex-col">
        <Provider>
          <header className=" border-b border-[#E2E8F0] h-15">
            <GNB />
          </header>
          <main className=" bg-gray-50 flex-1 flex flex-col ">
            <div className="lg:w-300 mx-auto flex-1 flex flex-col w-full">
              {children}
            </div>
          </main>
        </Provider>
      </body>
    </html>
  );
}
